// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/core/storage/document_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:aiscan/core/security/encryption_service.dart' as _i4;
import 'package:aiscan/core/security/secure_file_deletion_service.dart' as _i8;
import 'package:aiscan/core/storage/database_helper.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i4.EncryptionService {
  @override
  _i3.Future<_i5.Uint8List> encrypt(_i5.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [data],
        ),
        returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i3.Future<_i5.Uint8List>);

  @override
  _i3.Future<_i5.Uint8List> decrypt(_i5.Uint8List? encryptedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [encryptedData],
        ),
        returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i3.Future<_i5.Uint8List>);

  @override
  _i3.Future<_i5.Uint8List> decryptAsync(_i5.Uint8List? encryptedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptAsync,
          [encryptedData],
        ),
        returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i3.Future<_i5.Uint8List>);

  @override
  _i3.Future<void> encryptFile(
    String? inputPath,
    String? outputPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptFile,
          [
            inputPath,
            outputPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> decryptFile(
    String? inputPath,
    String? outputPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFile,
          [
            inputPath,
            outputPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> encryptString(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptString,
          [plaintext],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #encryptString,
            [plaintext],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #encryptString,
            [plaintext],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> decryptString(String? encryptedBase64) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptString,
          [encryptedBase64],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #decryptString,
            [encryptedBase64],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #decryptString,
            [encryptedBase64],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  bool isLikelyEncrypted(_i5.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #isLikelyEncrypted,
          [data],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<bool> ensureKeyInitialized() => (super.noSuchMethod(
        Invocation.method(
          #ensureKeyInitialized,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i7.DatabaseHelper {
  @override
  _i3.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i3.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i3.Future<_i2.Database>);

  @override
  bool get isFtsAvailable => (super.noSuchMethod(
        Invocation.getter(#isFtsAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> searchDocuments(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> rebuildFtsIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildFtsIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, dynamic>? values,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<dynamic>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> getById(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> count(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<T> transaction<T>(
          _i3.Future<T> Function(_i2.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
        returnValueForMissingStub: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> exists(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllTags({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPages,
          [documentId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getDocumentPagePaths(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPagePaths,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, List<String>>> getBatchDocumentPagePaths(
          List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDocumentPagePaths,
          [documentIds],
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
        returnValueForMissingStub: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getDocumentPage(
    String? documentId,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPage,
          [
            documentId,
            pageNumber,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> insertDocumentPage({
    required String? documentId,
    required int? pageNumber,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPage,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #filePath: filePath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> insertDocumentPages(
    String? documentId,
    List<String>? filePaths,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPages,
          [
            documentId,
            filePaths,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentPages,
          [documentId],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateDocumentPagePath({
    required String? documentId,
    required int? pageNumber,
    required String? newFilePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentPagePath,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #newFilePath: newFilePath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getDocumentPageCount(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPageCount,
          [documentId],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Map<String, List<String>>> getBatchDocumentTags(
          List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDocumentTags,
          [documentIds],
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
        returnValueForMissingStub: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<int> insertSearchHistory({
    required String? query,
    required String? timestamp,
    required int? resultCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSearchHistory,
          [],
          {
            #query: query,
            #timestamp: timestamp,
            #resultCount: resultCount,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getSearchHistory({
    int? limit,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {
            #limit: limit,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> deleteSearchHistory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSearchHistory,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [SecureFileDeletionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureFileDeletionService extends _i1.Mock
    implements _i8.SecureFileDeletionService {
  @override
  _i3.Future<bool> secureDeleteFile(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #secureDeleteFile,
          [filePath],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, bool>> secureDeleteFiles(List<String>? filePaths) =>
      (super.noSuchMethod(
        Invocation.method(
          #secureDeleteFiles,
          [filePaths],
        ),
        returnValue: _i3.Future<Map<String, bool>>.value(<String, bool>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i3.Future<Map<String, bool>>);
}
