// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/features/search/search_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i8;

import 'package:aiscan/core/storage/database_helper.dart' as _i5;
import 'package:aiscan/core/storage/document_repository.dart' as _i7;
import 'package:aiscan/features/documents/domain/document_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_2 extends _i1.SmartFake implements _i4.Document {
  _FakeDocument_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i5.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i3.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i3.Future<_i2.Database>);

  @override
  bool get isFtsAvailable => (super.noSuchMethod(
        Invocation.getter(#isFtsAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> searchDocuments(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> rebuildFtsIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildFtsIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, dynamic>? values,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<dynamic>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> getById(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> count(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<T> transaction<T>(
          _i3.Future<T> Function(_i2.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> exists(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllTags({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPages,
          [documentId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getDocumentPagePaths(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPagePaths,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, List<String>>> getBatchDocumentPagePaths(
          List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDocumentPagePaths,
          [documentIds],
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getDocumentPage(
    String? documentId,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPage,
          [
            documentId,
            pageNumber,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> insertDocumentPage({
    required String? documentId,
    required int? pageNumber,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPage,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #filePath: filePath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> insertDocumentPages(
    String? documentId,
    List<String>? filePaths,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPages,
          [
            documentId,
            filePaths,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentPages,
          [documentId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateDocumentPagePath({
    required String? documentId,
    required int? pageNumber,
    required String? newFilePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentPagePath,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #newFilePath: newFilePath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getDocumentPageCount(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPageCount,
          [documentId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Map<String, List<String>>> getBatchDocumentTags(
          List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDocumentTags,
          [documentIds],
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<int> insertSearchHistory({
    required String? query,
    required String? timestamp,
    required int? resultCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSearchHistory,
          [],
          {
            #query: query,
            #timestamp: timestamp,
            #resultCount: resultCount,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getSearchHistory({
    int? limit,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {
            #limit: limit,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> deleteSearchHistory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSearchHistory,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i7.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Document> createDocumentWithPages({
    required String? title,
    required List<String>? sourceImagePaths,
    String? description,
    String? thumbnailSourcePath,
    String? folderId,
    bool? isFavorite = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocumentWithPages,
          [],
          {
            #title: title,
            #sourceImagePaths: sourceImagePaths,
            #description: description,
            #thumbnailSourcePath: thumbnailSourcePath,
            #folderId: folderId,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #createDocumentWithPages,
            [],
            {
              #title: title,
              #sourceImagePaths: sourceImagePaths,
              #description: description,
              #thumbnailSourcePath: thumbnailSourcePath,
              #folderId: folderId,
              #isFavorite: isFavorite,
            },
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document?> getDocument(
    String? id, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<_i4.Document?>.value(),
      ) as _i3.Future<_i4.Document?>);

  @override
  _i3.Future<List<_i4.Document>> getAllDocuments({
    bool? includeTags = false,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> getDocumentsInFolder(
    String? folderId, {
    bool? includeTags = false,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsInFolder,
          [folderId],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> getFavoriteDocuments(
          {bool? includeTags = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDocuments,
          [],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<int> getDocumentCount() => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getDecryptedPagePath(
    _i4.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPagePath,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getDecryptedPagePath,
            [document],
            {#pageIndex: pageIndex},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<String>> getDecryptedAllPages(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedAllPages,
          [document],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<int>> getDecryptedPageBytes(
    _i4.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPageBytes,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<_i8.Uint8List?> getDecryptedThumbnailBytes(
          _i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailBytes,
          [document],
        ),
        returnValue: _i3.Future<_i8.Uint8List?>.value(),
      ) as _i3.Future<_i8.Uint8List?>);

  @override
  _i3.Future<Map<String, _i8.Uint8List>> getBatchDecryptedThumbnailBytes(
          List<_i4.Document>? documents) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDecryptedThumbnailBytes,
          [documents],
        ),
        returnValue: _i3.Future<Map<String, _i8.Uint8List>>.value(
            <String, _i8.Uint8List>{}),
      ) as _i3.Future<Map<String, _i8.Uint8List>>);

  @override
  _i3.Future<String?> getDecryptedThumbnailPath(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailPath,
          [document],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i4.Document> updateDocument(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocument,
            [document],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentThumbnail(
    _i4.Document? document,
    String? newThumbnailPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentThumbnail,
          [
            document,
            newThumbnailPath,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentThumbnail,
            [
              document,
              newThumbnailPath,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentOcr(
    String? documentId,
    String? ocrText, {
    _i4.OcrStatus? status = _i4.OcrStatus.completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentOcr,
          [
            documentId,
            ocrText,
          ],
          {#status: status},
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentOcr,
            [
              documentId,
              ocrText,
            ],
            {#status: status},
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> toggleFavorite(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [documentId],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #toggleFavorite,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> moveToFolder(
    String? documentId,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToFolder,
          [
            documentId,
            folderId,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #moveToFolder,
            [
              documentId,
              folderId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<void> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocuments(List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocuments,
          [documentIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getDocumentTags(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentTags,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> addTagToDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTagFromDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Document>> getDocumentsByTag(
    String? tagId, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByTag,
          [tagId],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> searchDocuments(
    String? query, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<void> cleanupTempFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTempFiles,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
