// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/features/scanner/scanner_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aiscan/core/storage/document_repository.dart' as _i3;
import 'package:aiscan/features/documents/domain/document_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocument_0 extends _i1.SmartFake implements _i2.Document {
  _FakeDocument_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i3.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Document> createDocumentWithPages({
    required String? title,
    required List<String>? sourceImagePaths,
    String? description,
    String? thumbnailSourcePath,
    String? folderId,
    bool? isFavorite = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocumentWithPages,
          [],
          {
            #title: title,
            #sourceImagePaths: sourceImagePaths,
            #description: description,
            #thumbnailSourcePath: thumbnailSourcePath,
            #folderId: folderId,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i4.Future<_i2.Document>.value(_FakeDocument_0(
          this,
          Invocation.method(
            #createDocumentWithPages,
            [],
            {
              #title: title,
              #sourceImagePaths: sourceImagePaths,
              #description: description,
              #thumbnailSourcePath: thumbnailSourcePath,
              #folderId: folderId,
              #isFavorite: isFavorite,
            },
          ),
        )),
      ) as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i2.Document?> getDocument(
    String? id, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
          {#includeTags: includeTags},
        ),
        returnValue: _i4.Future<_i2.Document?>.value(),
      ) as _i4.Future<_i2.Document?>);

  @override
  _i4.Future<List<_i2.Document>> getAllDocuments({
    bool? includeTags = false,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i4.Future<List<_i2.Document>>);

  @override
  _i4.Future<List<_i2.Document>> getDocumentsInFolder(
    String? folderId, {
    bool? includeTags = false,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsInFolder,
          [folderId],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i4.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i4.Future<List<_i2.Document>>);

  @override
  _i4.Future<List<_i2.Document>> getFavoriteDocuments(
          {bool? includeTags = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDocuments,
          [],
          {#includeTags: includeTags},
        ),
        returnValue: _i4.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i4.Future<List<_i2.Document>>);

  @override
  _i4.Future<int> getDocumentCount() => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<String> getDecryptedPagePath(
    _i2.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPagePath,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDecryptedPagePath,
            [document],
            {#pageIndex: pageIndex},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<String>> getDecryptedAllPages(_i2.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedAllPages,
          [document],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<int>> getDecryptedPageBytes(
    _i2.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPageBytes,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<String?> getDecryptedThumbnailPath(_i2.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailPath,
          [document],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i2.Document> updateDocument(_i2.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i4.Future<_i2.Document>.value(_FakeDocument_0(
          this,
          Invocation.method(
            #updateDocument,
            [document],
          ),
        )),
      ) as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i2.Document> updateDocumentThumbnail(
    _i2.Document? document,
    String? newThumbnailPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentThumbnail,
          [
            document,
            newThumbnailPath,
          ],
        ),
        returnValue: _i4.Future<_i2.Document>.value(_FakeDocument_0(
          this,
          Invocation.method(
            #updateDocumentThumbnail,
            [
              document,
              newThumbnailPath,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i2.Document> updateDocumentOcr(
    String? documentId,
    String? ocrText, {
    _i2.OcrStatus? status = _i2.OcrStatus.completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentOcr,
          [
            documentId,
            ocrText,
          ],
          {#status: status},
        ),
        returnValue: _i4.Future<_i2.Document>.value(_FakeDocument_0(
          this,
          Invocation.method(
            #updateDocumentOcr,
            [
              documentId,
              ocrText,
            ],
            {#status: status},
          ),
        )),
      ) as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i2.Document> toggleFavorite(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [documentId],
        ),
        returnValue: _i4.Future<_i2.Document>.value(_FakeDocument_0(
          this,
          Invocation.method(
            #toggleFavorite,
            [documentId],
          ),
        )),
      ) as _i4.Future<_i2.Document>);

  @override
  _i4.Future<_i2.Document> moveToFolder(
    String? documentId,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToFolder,
          [
            documentId,
            folderId,
          ],
        ),
        returnValue: _i4.Future<_i2.Document>.value(_FakeDocument_0(
          this,
          Invocation.method(
            #moveToFolder,
            [
              documentId,
              folderId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Document>);

  @override
  _i4.Future<void> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDocuments(List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocuments,
          [documentIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getDocumentTags(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentTags,
          [documentId],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addTagToDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeTagFromDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Document>> getDocumentsByTag(
    String? tagId, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByTag,
          [tagId],
          {#includeTags: includeTags},
        ),
        returnValue: _i4.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i4.Future<List<_i2.Document>>);

  @override
  _i4.Future<List<_i2.Document>> searchDocuments(
    String? query, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
          {#includeTags: includeTags},
        ),
        returnValue: _i4.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i4.Future<List<_i2.Document>>);

  @override
  _i4.Future<void> cleanupTempFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTempFiles,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
