// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/core/security/encryption_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:aiscan/core/security/secure_storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i2.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeEncryptionKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #storeEncryptionKey,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getInitializationVector() => (super.noSuchMethod(
        Invocation.method(
          #getInitializationVector,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeInitializationVector(String? iv) => (super.noSuchMethod(
        Invocation.method(
          #storeInitializationVector,
          [iv],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getSalt() => (super.noSuchMethod(
        Invocation.method(
          #getSalt,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeSalt(String? salt) => (super.noSuchMethod(
        Invocation.method(
          #storeSalt,
          [salt],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getOrCreateEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateEncryptionKey,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getOrCreateInitializationVector() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateInitializationVector,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateInitializationVector,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getOrCreateSalt() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateSalt,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateSalt,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> storeUserData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [key],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #hasEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i5.Uint8List decodeKey(String? base64Key) => (super.noSuchMethod(
        Invocation.method(
          #decodeKey,
          [base64Key],
        ),
        returnValue: _i5.Uint8List(0),
      ) as _i5.Uint8List);

  @override
  String encodeBytes(_i5.Uint8List? bytes) => (super.noSuchMethod(
        Invocation.method(
          #encodeBytes,
          [bytes],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #encodeBytes,
            [bytes],
          ),
        ),
      ) as String);
}
