// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/e2e/complete_user_flows_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i14;

import 'package:aiscan/core/security/encryption_service.dart' as _i15;
import 'package:aiscan/core/security/secure_storage_service.dart' as _i12;
import 'package:aiscan/core/storage/database_helper.dart' as _i16;
import 'package:aiscan/core/storage/document_repository.dart' as _i17;
import 'package:aiscan/features/documents/domain/document_model.dart' as _i4;
import 'package:aiscan/features/enhancement/domain/image_processor.dart' as _i9;
import 'package:aiscan/features/export/domain/image_exporter.dart' as _i11;
import 'package:aiscan/features/export/domain/pdf_generator.dart' as _i10;
import 'package:aiscan/features/folders/domain/folder_model.dart' as _i7;
import 'package:aiscan/features/folders/domain/folder_service.dart' as _i8;
import 'package:aiscan/features/ocr/domain/ocr_service.dart' as _i5;
import 'package:aiscan/features/search/domain/search_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_2 extends _i1.SmartFake implements _i4.Document {
  _FakeDocument_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOcrResult_3 extends _i1.SmartFake implements _i5.OcrResult {
  _FakeOcrResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResults_4 extends _i1.SmartFake implements _i6.SearchResults {
  _FakeSearchResults_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFolder_5 extends _i1.SmartFake implements _i7.Folder {
  _FakeFolder_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFolderStats_6 extends _i1.SmartFake implements _i8.FolderStats {
  _FakeFolderStats_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProcessedImage_7 extends _i1.SmartFake
    implements _i9.ProcessedImage {
  _FakeProcessedImage_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageInfo_8 extends _i1.SmartFake implements _i9.ImageInfo {
  _FakeImageInfo_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedPDF_9 extends _i1.SmartFake implements _i10.GeneratedPDF {
  _FakeGeneratedPDF_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExportedImage_10 extends _i1.SmartFake
    implements _i11.ExportedImage {
  _FakeExportedImage_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchExportResult_11 extends _i1.SmartFake
    implements _i11.BatchExportResult {
  _FakeBatchExportResult_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i12.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeEncryptionKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #storeEncryptionKey,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getInitializationVector() => (super.noSuchMethod(
        Invocation.method(
          #getInitializationVector,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeInitializationVector(String? iv) => (super.noSuchMethod(
        Invocation.method(
          #storeInitializationVector,
          [iv],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getSalt() => (super.noSuchMethod(
        Invocation.method(
          #getSalt,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeSalt(String? salt) => (super.noSuchMethod(
        Invocation.method(
          #storeSalt,
          [salt],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getOrCreateEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateEncryptionKey,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getOrCreateInitializationVector() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateInitializationVector,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateInitializationVector,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getOrCreateSalt() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateSalt,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateSalt,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> storeUserData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [key],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #hasEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i14.Uint8List decodeKey(String? base64Key) => (super.noSuchMethod(
        Invocation.method(
          #decodeKey,
          [base64Key],
        ),
        returnValue: _i14.Uint8List(0),
      ) as _i14.Uint8List);

  @override
  String encodeBytes(_i14.Uint8List? bytes) => (super.noSuchMethod(
        Invocation.method(
          #encodeBytes,
          [bytes],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #encodeBytes,
            [bytes],
          ),
        ),
      ) as String);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i15.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i14.Uint8List> encrypt(_i14.Uint8List? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [data],
        ),
        returnValue: _i3.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i3.Future<_i14.Uint8List>);

  @override
  _i3.Future<_i14.Uint8List> decrypt(_i14.Uint8List? encryptedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [encryptedData],
        ),
        returnValue: _i3.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i3.Future<_i14.Uint8List>);

  @override
  _i3.Future<void> encryptFile(
    String? inputPath,
    String? outputPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptFile,
          [
            inputPath,
            outputPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> decryptFile(
    String? inputPath,
    String? outputPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFile,
          [
            inputPath,
            outputPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> encryptString(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptString,
          [plaintext],
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #encryptString,
            [plaintext],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> decryptString(String? encryptedBase64) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptString,
          [encryptedBase64],
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #decryptString,
            [encryptedBase64],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  bool isLikelyEncrypted(_i14.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #isLikelyEncrypted,
          [data],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> ensureKeyInitialized() => (super.noSuchMethod(
        Invocation.method(
          #ensureKeyInitialized,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i16.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i3.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i3.Future<_i2.Database>);

  @override
  bool get isFtsAvailable => (super.noSuchMethod(
        Invocation.getter(#isFtsAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> searchDocuments(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> rebuildFtsIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildFtsIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, dynamic>? values,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<dynamic>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> getById(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> count(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<T> transaction<T>(
          _i3.Future<T> Function(_i2.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i13.ifNotNull(
              _i13.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> exists(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllTags({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPages,
          [documentId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getDocumentPagePaths(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPagePaths,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, dynamic>?> getDocumentPage(
    String? documentId,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPage,
          [
            documentId,
            pageNumber,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> insertDocumentPage({
    required String? documentId,
    required int? pageNumber,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPage,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #filePath: filePath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> insertDocumentPages(
    String? documentId,
    List<String>? filePaths,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPages,
          [
            documentId,
            filePaths,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentPages,
          [documentId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateDocumentPagePath({
    required String? documentId,
    required int? pageNumber,
    required String? newFilePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentPagePath,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #newFilePath: newFilePath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getDocumentPageCount(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPageCount,
          [documentId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> insertSearchHistory({
    required String? query,
    required String? timestamp,
    required int? resultCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSearchHistory,
          [],
          {
            #query: query,
            #timestamp: timestamp,
            #resultCount: resultCount,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getSearchHistory({
    int? limit,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {
            #limit: limit,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> deleteSearchHistory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSearchHistory,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i17.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Document> createDocumentWithPages({
    required String? title,
    required List<String>? sourceImagePaths,
    String? description,
    String? thumbnailSourcePath,
    String? folderId,
    bool? isFavorite = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocumentWithPages,
          [],
          {
            #title: title,
            #sourceImagePaths: sourceImagePaths,
            #description: description,
            #thumbnailSourcePath: thumbnailSourcePath,
            #folderId: folderId,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #createDocumentWithPages,
            [],
            {
              #title: title,
              #sourceImagePaths: sourceImagePaths,
              #description: description,
              #thumbnailSourcePath: thumbnailSourcePath,
              #folderId: folderId,
              #isFavorite: isFavorite,
            },
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document?> getDocument(
    String? id, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<_i4.Document?>.value(),
      ) as _i3.Future<_i4.Document?>);

  @override
  _i3.Future<List<_i4.Document>> getAllDocuments({
    bool? includeTags = false,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> getDocumentsInFolder(
    String? folderId, {
    bool? includeTags = false,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsInFolder,
          [folderId],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> getFavoriteDocuments(
          {bool? includeTags = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDocuments,
          [],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<int> getDocumentCount() => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getDecryptedPagePath(
    _i4.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPagePath,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getDecryptedPagePath,
            [document],
            {#pageIndex: pageIndex},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<String>> getDecryptedAllPages(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedAllPages,
          [document],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<int>> getDecryptedPageBytes(
    _i4.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPageBytes,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<String?> getDecryptedThumbnailPath(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailPath,
          [document],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i4.Document> updateDocument(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocument,
            [document],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentThumbnail(
    _i4.Document? document,
    String? newThumbnailPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentThumbnail,
          [
            document,
            newThumbnailPath,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentThumbnail,
            [
              document,
              newThumbnailPath,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentOcr(
    String? documentId,
    String? ocrText, {
    _i4.OcrStatus? status = _i4.OcrStatus.completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentOcr,
          [
            documentId,
            ocrText,
          ],
          {#status: status},
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentOcr,
            [
              documentId,
              ocrText,
            ],
            {#status: status},
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> toggleFavorite(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [documentId],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #toggleFavorite,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> moveToFolder(
    String? documentId,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToFolder,
          [
            documentId,
            folderId,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #moveToFolder,
            [
              documentId,
              folderId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<void> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocuments(List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocuments,
          [documentIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getDocumentTags(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentTags,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> addTagToDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTagFromDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Document>> getDocumentsByTag(
    String? tagId, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByTag,
          [tagId],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> searchDocuments(
    String? query, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<void> cleanupTempFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTempFiles,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [OcrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOcrService extends _i1.Mock implements _i5.OcrService {
  MockOcrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.OcrLanguage> get availableLanguages => (super.noSuchMethod(
        Invocation.getter(#availableLanguages),
        returnValue: <_i5.OcrLanguage>[],
      ) as List<_i5.OcrLanguage>);

  @override
  _i3.Future<bool> initialize(
          {List<_i5.OcrLanguage>? languages = const [_i5.OcrLanguage.latin]}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#languages: languages},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  bool isLanguageAvailable(_i5.OcrLanguage? language) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageAvailable,
          [language],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i5.OcrResult> extractTextFromFile(
    String? imagePath, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromFile,
          [imagePath],
          {#options: options},
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextFromFile,
            [imagePath],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<_i5.OcrResult> extractTextFromBytes(
    _i14.Uint8List? bytes, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromBytes,
          [bytes],
          {#options: options},
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextFromBytes,
            [bytes],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<_i5.OcrResult> extractTextFromMultipleFiles(
    List<String>? imagePaths, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
    String? separator = '\n\n',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromMultipleFiles,
          [imagePaths],
          {
            #options: options,
            #separator: separator,
          },
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextFromMultipleFiles,
            [imagePaths],
            {
              #options: options,
              #separator: separator,
            },
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<_i5.OcrResult> extractTextWithProgress(
    List<String>? imagePaths, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
    required void Function(
      int,
      int,
      _i5.OcrResult,
    )? onProgress,
    String? separator = '\n\n',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextWithProgress,
          [imagePaths],
          {
            #options: options,
            #onProgress: onProgress,
            #separator: separator,
          },
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextWithProgress,
            [imagePaths],
            {
              #options: options,
              #onProgress: onProgress,
              #separator: separator,
            },
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<bool> containsText(
    String? imagePath, {
    _i5.OcrLanguage? language = _i5.OcrLanguage.latin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsText,
          [imagePath],
          {#language: language},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getCacheSizeFormatted() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSizeFormatted,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #getCacheSizeFormatted,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i6.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.RecentSearch> get recentSearches => (super.noSuchMethod(
        Invocation.getter(#recentSearches),
        returnValue: <_i6.RecentSearch>[],
      ) as List<_i6.RecentSearch>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i6.SearchResults> search(
    String? query, {
    _i6.SearchOptions? options = const _i6.SearchOptions.defaults(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#options: options},
        ),
        returnValue: _i3.Future<_i6.SearchResults>.value(_FakeSearchResults_4(
          this,
          Invocation.method(
            #search,
            [query],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i6.SearchResults>);

  @override
  _i3.Future<List<String>> getSuggestions(
    String? partialQuery, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [partialQuery],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i6.RecentSearch>> getRecentSearches({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i3.Future<List<_i6.RecentSearch>>.value(<_i6.RecentSearch>[]),
      ) as _i3.Future<List<_i6.RecentSearch>>);

  @override
  _i3.Future<void> clearRecentSearches() => (super.noSuchMethod(
        Invocation.method(
          #clearRecentSearches,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeRecentSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #removeRecentSearch,
          [query],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rebuildIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getIndexSize() => (super.noSuchMethod(
        Invocation.method(
          #getIndexSize,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [FolderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderService extends _i1.Mock implements _i8.FolderService {
  MockFolderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.Folder> createFolder({
    required String? name,
    String? parentId,
    String? color,
    String? icon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [],
          {
            #name: name,
            #parentId: parentId,
            #color: color,
            #icon: icon,
          },
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #createFolder,
            [],
            {
              #name: name,
              #parentId: parentId,
              #color: color,
              #icon: icon,
            },
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder?> getFolder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFolder,
          [id],
        ),
        returnValue: _i3.Future<_i7.Folder?>.value(),
      ) as _i3.Future<_i7.Folder?>);

  @override
  _i3.Future<List<_i7.Folder>> getAllFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getRootFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRootFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getChildFolders(
    String? parentId, {
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildFolders,
          [parentId],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getDescendantFolders(String? parentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDescendantFolders,
          [parentId],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getFolderPath(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderPath,
          [folderId],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<int> getFolderDepth(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getFolderDepth,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getFolderCount() => (super.noSuchMethod(
        Invocation.method(
          #getFolderCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> folderExists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #folderExists,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getDocumentCount(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i8.FolderStats> getFolderStats(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderStats,
          [folderId],
        ),
        returnValue: _i3.Future<_i8.FolderStats>.value(_FakeFolderStats_6(
          this,
          Invocation.method(
            #getFolderStats,
            [folderId],
          ),
        )),
      ) as _i3.Future<_i8.FolderStats>);

  @override
  _i3.Future<bool> isFolderEmpty(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #isFolderEmpty,
          [folderId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i7.Folder> updateFolder(_i7.Folder? folder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolder,
          [folder],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #updateFolder,
            [folder],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> renameFolder(
    String? folderId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [
            folderId,
            newName,
          ],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #renameFolder,
            [
              folderId,
              newName,
            ],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> updateFolderColor(
    String? folderId,
    String? color,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolderColor,
          [
            folderId,
            color,
          ],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #updateFolderColor,
            [
              folderId,
              color,
            ],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> updateFolderIcon(
    String? folderId,
    String? icon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolderIcon,
          [
            folderId,
            icon,
          ],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #updateFolderIcon,
            [
              folderId,
              icon,
            ],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> toggleFavorite(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [folderId],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #toggleFavorite,
            [folderId],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<List<_i7.Folder>> setFavoriteForFolders(
    List<String>? folderIds,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFavoriteForFolders,
          [
            folderIds,
            isFavorite,
          ],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<_i7.Folder> moveFolder(
    String? folderId, {
    String? newParentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFolder,
          [folderId],
          {#newParentId: newParentId},
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #moveFolder,
            [folderId],
            {#newParentId: newParentId},
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<void> deleteFolder(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [folderId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteFolderRecursive(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolderRecursive,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteFolders(List<String>? folderIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolders,
          [folderIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Folder>> searchFolders(
    String? query, {
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFolders,
          [query],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<(_i7.Folder, int)>> getFolderHierarchy() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderHierarchy,
          [],
        ),
        returnValue:
            _i3.Future<List<(_i7.Folder, int)>>.value(<(_i7.Folder, int)>[]),
      ) as _i3.Future<List<(_i7.Folder, int)>>);

  @override
  _i3.Future<List<_i7.Folder>> getSelectableFolders(String? excludeFolderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectableFolders,
          [excludeFolderId],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);
}

/// A class which mocks [ImageProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProcessor extends _i1.Mock implements _i9.ImageProcessor {
  MockImageProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i9.ProcessedImage> enhanceFromFile(
    String? filePath, {
    _i9.EnhancementOptions? options = _i9.EnhancementOptions.none,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enhanceFromFile,
          [filePath],
          {
            #options: options,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #enhanceFromFile,
            [filePath],
            {
              #options: options,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> enhanceFromBytes(
    _i14.Uint8List? bytes, {
    _i9.EnhancementOptions? options = _i9.EnhancementOptions.none,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enhanceFromBytes,
          [bytes],
          {
            #options: options,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #enhanceFromBytes,
            [bytes],
            {
              #options: options,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> enhanceFromFileToFile(
    String? inputPath,
    String? outputPath, {
    _i9.EnhancementOptions? options = _i9.EnhancementOptions.none,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enhanceFromFileToFile,
          [
            inputPath,
            outputPath,
          ],
          {
            #options: options,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #enhanceFromFileToFile,
            [
              inputPath,
              outputPath,
            ],
            {
              #options: options,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> autoEnhance(
    _i14.Uint8List? bytes, {
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoEnhance,
          [bytes],
          {
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #autoEnhance,
            [bytes],
            {
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> convertToGrayscale(
    _i14.Uint8List? bytes, {
    bool? enhanceContrast = true,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertToGrayscale,
          [bytes],
          {
            #enhanceContrast: enhanceContrast,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #convertToGrayscale,
            [bytes],
            {
              #enhanceContrast: enhanceContrast,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> sharpen(
    _i14.Uint8List? bytes, {
    int? amount = 50,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sharpen,
          [bytes],
          {
            #amount: amount,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #sharpen,
            [bytes],
            {
              #amount: amount,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> adjustBrightness(
    _i14.Uint8List? bytes, {
    required int? amount,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustBrightness,
          [bytes],
          {
            #amount: amount,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #adjustBrightness,
            [bytes],
            {
              #amount: amount,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> adjustContrast(
    _i14.Uint8List? bytes, {
    required int? amount,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustContrast,
          [bytes],
          {
            #amount: amount,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #adjustContrast,
            [bytes],
            {
              #amount: amount,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> resize(
    _i14.Uint8List? bytes, {
    required int? maxWidth,
    required int? maxHeight,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resize,
          [bytes],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #resize,
            [bytes],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> crop(
    _i14.Uint8List? bytes, {
    required int? x,
    required int? y,
    required int? width,
    required int? height,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #crop,
          [bytes],
          {
            #x: x,
            #y: y,
            #width: width,
            #height: height,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #crop,
            [bytes],
            {
              #x: x,
              #y: y,
              #width: width,
              #height: height,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ProcessedImage> rotate(
    _i14.Uint8List? bytes, {
    required double? angle,
    _i9.ImageOutputFormat? outputFormat = _i9.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotate,
          [bytes],
          {
            #angle: angle,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<_i9.ProcessedImage>.value(_FakeProcessedImage_7(
          this,
          Invocation.method(
            #rotate,
            [bytes],
            {
              #angle: angle,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i9.ProcessedImage>);

  @override
  _i3.Future<_i9.ImageInfo> getImageInfo(_i14.Uint8List? bytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageInfo,
          [bytes],
        ),
        returnValue: _i3.Future<_i9.ImageInfo>.value(_FakeImageInfo_8(
          this,
          Invocation.method(
            #getImageInfo,
            [bytes],
          ),
        )),
      ) as _i3.Future<_i9.ImageInfo>);
}

/// A class which mocks [PDFGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPDFGenerator extends _i1.Mock implements _i10.PDFGenerator {
  MockPDFGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i10.GeneratedPDF> generateFromBytes({
    required List<_i14.Uint8List>? imageBytesList,
    _i10.PDFGeneratorOptions? options = const _i10.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromBytes,
          [],
          {
            #imageBytesList: imageBytesList,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i10.GeneratedPDF>.value(_FakeGeneratedPDF_9(
          this,
          Invocation.method(
            #generateFromBytes,
            [],
            {
              #imageBytesList: imageBytesList,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i10.GeneratedPDF>);

  @override
  _i3.Future<_i10.GeneratedPDF> generateFromFiles({
    required List<String>? imagePaths,
    _i10.PDFGeneratorOptions? options = const _i10.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromFiles,
          [],
          {
            #imagePaths: imagePaths,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i10.GeneratedPDF>.value(_FakeGeneratedPDF_9(
          this,
          Invocation.method(
            #generateFromFiles,
            [],
            {
              #imagePaths: imagePaths,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i10.GeneratedPDF>);

  @override
  _i3.Future<_i10.GeneratedPDF> generateFromPages({
    required List<_i10.PDFPage>? pages,
    _i10.PDFGeneratorOptions? options = const _i10.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromPages,
          [],
          {
            #pages: pages,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i10.GeneratedPDF>.value(_FakeGeneratedPDF_9(
          this,
          Invocation.method(
            #generateFromPages,
            [],
            {
              #pages: pages,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i10.GeneratedPDF>);

  @override
  _i3.Future<_i10.GeneratedPDF> generateToFile({
    required List<String>? imagePaths,
    required String? outputPath,
    _i10.PDFGeneratorOptions? options = const _i10.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateToFile,
          [],
          {
            #imagePaths: imagePaths,
            #outputPath: outputPath,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i10.GeneratedPDF>.value(_FakeGeneratedPDF_9(
          this,
          Invocation.method(
            #generateToFile,
            [],
            {
              #imagePaths: imagePaths,
              #outputPath: outputPath,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i10.GeneratedPDF>);

  @override
  _i3.Future<_i10.GeneratedPDF> generateSinglePage({
    required _i14.Uint8List? imageBytes,
    _i10.PDFGeneratorOptions? options = const _i10.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSinglePage,
          [],
          {
            #imageBytes: imageBytes,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i10.GeneratedPDF>.value(_FakeGeneratedPDF_9(
          this,
          Invocation.method(
            #generateSinglePage,
            [],
            {
              #imageBytes: imageBytes,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i10.GeneratedPDF>);

  @override
  _i3.Future<_i10.GeneratedPDF> generateSinglePageFromFile({
    required String? imagePath,
    _i10.PDFGeneratorOptions? options = const _i10.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSinglePageFromFile,
          [],
          {
            #imagePath: imagePath,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i10.GeneratedPDF>.value(_FakeGeneratedPDF_9(
          this,
          Invocation.method(
            #generateSinglePageFromFile,
            [],
            {
              #imagePath: imagePath,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i10.GeneratedPDF>);
}

/// A class which mocks [ImageExporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageExporter extends _i1.Mock implements _i11.ImageExporter {
  MockImageExporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i11.ExportedImage> exportFromBytes(
    _i14.Uint8List? bytes, {
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
    String? originalFileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFromBytes,
          [bytes],
          {
            #options: options,
            #originalFileName: originalFileName,
          },
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #exportFromBytes,
            [bytes],
            {
              #options: options,
              #originalFileName: originalFileName,
            },
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.ExportedImage> exportFromFile(
    String? filePath, {
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFromFile,
          [filePath],
          {#options: options},
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #exportFromFile,
            [filePath],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.ExportedImage> exportToFile(
    _i14.Uint8List? bytes, {
    required String? outputPath,
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToFile,
          [bytes],
          {
            #outputPath: outputPath,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #exportToFile,
            [bytes],
            {
              #outputPath: outputPath,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.ExportedImage> exportFileToFile(
    String? inputPath,
    String? outputPath, {
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFileToFile,
          [
            inputPath,
            outputPath,
          ],
          {#options: options},
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #exportFileToFile,
            [
              inputPath,
              outputPath,
            ],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.BatchExportResult> exportBatch({
    required List<_i14.Uint8List>? imageBytesList,
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBatch,
          [],
          {
            #imageBytesList: imageBytesList,
            #options: options,
          },
        ),
        returnValue:
            _i3.Future<_i11.BatchExportResult>.value(_FakeBatchExportResult_11(
          this,
          Invocation.method(
            #exportBatch,
            [],
            {
              #imageBytesList: imageBytesList,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i11.BatchExportResult>);

  @override
  _i3.Future<_i11.BatchExportResult> exportBatchFromFiles({
    required List<String>? imagePaths,
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBatchFromFiles,
          [],
          {
            #imagePaths: imagePaths,
            #options: options,
          },
        ),
        returnValue:
            _i3.Future<_i11.BatchExportResult>.value(_FakeBatchExportResult_11(
          this,
          Invocation.method(
            #exportBatchFromFiles,
            [],
            {
              #imagePaths: imagePaths,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i11.BatchExportResult>);

  @override
  _i3.Future<_i11.BatchExportResult> exportBatchToDirectory({
    required List<_i14.Uint8List>? imageBytesList,
    required String? outputDirectory,
    String? baseName = 'scan',
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBatchToDirectory,
          [],
          {
            #imageBytesList: imageBytesList,
            #outputDirectory: outputDirectory,
            #baseName: baseName,
            #options: options,
          },
        ),
        returnValue:
            _i3.Future<_i11.BatchExportResult>.value(_FakeBatchExportResult_11(
          this,
          Invocation.method(
            #exportBatchToDirectory,
            [],
            {
              #imageBytesList: imageBytesList,
              #outputDirectory: outputDirectory,
              #baseName: baseName,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i11.BatchExportResult>);

  @override
  _i3.Future<_i11.ExportedImage> createThumbnail(
    _i14.Uint8List? bytes, {
    int? maxWidth = 300,
    int? maxHeight = 300,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThumbnail,
          [bytes],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #createThumbnail,
            [bytes],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
            },
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.ExportedImage> createPreview(
    _i14.Uint8List? bytes, {
    int? maxWidth = 800,
    int? maxHeight = 800,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPreview,
          [bytes],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #createPreview,
            [bytes],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
            },
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.ExportedImage> stitchVertical({
    required List<_i14.Uint8List>? imageBytesList,
    int? spacing = 0,
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stitchVertical,
          [],
          {
            #imageBytesList: imageBytesList,
            #spacing: spacing,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #stitchVertical,
            [],
            {
              #imageBytesList: imageBytesList,
              #spacing: spacing,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);

  @override
  _i3.Future<_i11.ExportedImage> stitchHorizontal({
    required List<_i14.Uint8List>? imageBytesList,
    int? spacing = 0,
    _i11.ImageExportOptions? options = const _i11.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stitchHorizontal,
          [],
          {
            #imageBytesList: imageBytesList,
            #spacing: spacing,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i11.ExportedImage>.value(_FakeExportedImage_10(
          this,
          Invocation.method(
            #stitchHorizontal,
            [],
            {
              #imageBytesList: imageBytesList,
              #spacing: spacing,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i11.ExportedImage>);
}
