// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/e2e/complete_user_flows_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i16;
import 'dart:ui' as _i20;

import 'package:aiscan/core/security/encryption_service.dart' as _i17;
import 'package:aiscan/core/security/secure_storage_service.dart' as _i14;
import 'package:aiscan/core/storage/database_helper.dart' as _i18;
import 'package:aiscan/core/storage/document_repository.dart' as _i19;
import 'package:aiscan/features/documents/domain/document_model.dart' as _i4;
import 'package:aiscan/features/enhancement/domain/image_processor.dart'
    as _i11;
import 'package:aiscan/features/export/domain/image_exporter.dart' as _i13;
import 'package:aiscan/features/export/domain/pdf_generator.dart' as _i12;
import 'package:aiscan/features/folders/domain/folder_model.dart' as _i7;
import 'package:aiscan/features/folders/domain/folder_service.dart' as _i8;
import 'package:aiscan/features/ocr/domain/ocr_service.dart' as _i5;
import 'package:aiscan/features/search/domain/search_service.dart' as _i6;
import 'package:aiscan/features/signature/domain/signature_service.dart'
    as _i10;
import 'package:hand_signature/signature.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_2 extends _i1.SmartFake implements _i4.Document {
  _FakeDocument_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOcrResult_3 extends _i1.SmartFake implements _i5.OcrResult {
  _FakeOcrResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResults_4 extends _i1.SmartFake implements _i6.SearchResults {
  _FakeSearchResults_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFolder_5 extends _i1.SmartFake implements _i7.Folder {
  _FakeFolder_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFolderStats_6 extends _i1.SmartFake implements _i8.FolderStats {
  _FakeFolderStats_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHandSignatureControl_7 extends _i1.SmartFake
    implements _i9.HandSignatureControl {
  _FakeHandSignatureControl_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCapturedSignature_8 extends _i1.SmartFake
    implements _i10.CapturedSignature {
  _FakeCapturedSignature_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSavedSignature_9 extends _i1.SmartFake
    implements _i10.SavedSignature {
  _FakeSavedSignature_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignedDocument_10 extends _i1.SmartFake
    implements _i10.SignedDocument {
  _FakeSignedDocument_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProcessedImage_11 extends _i1.SmartFake
    implements _i11.ProcessedImage {
  _FakeProcessedImage_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageInfo_12 extends _i1.SmartFake implements _i11.ImageInfo {
  _FakeImageInfo_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedPDF_13 extends _i1.SmartFake implements _i12.GeneratedPDF {
  _FakeGeneratedPDF_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExportedImage_14 extends _i1.SmartFake
    implements _i13.ExportedImage {
  _FakeExportedImage_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchExportResult_15 extends _i1.SmartFake
    implements _i13.BatchExportResult {
  _FakeBatchExportResult_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i14.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeEncryptionKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #storeEncryptionKey,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getInitializationVector() => (super.noSuchMethod(
        Invocation.method(
          #getInitializationVector,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeInitializationVector(String? iv) => (super.noSuchMethod(
        Invocation.method(
          #storeInitializationVector,
          [iv],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getSalt() => (super.noSuchMethod(
        Invocation.method(
          #getSalt,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeSalt(String? salt) => (super.noSuchMethod(
        Invocation.method(
          #storeSalt,
          [salt],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getOrCreateEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateEncryptionKey,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getOrCreateInitializationVector() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateInitializationVector,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateInitializationVector,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getOrCreateSalt() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateSalt,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateSalt,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> storeUserData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [key],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #hasEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i16.Uint8List decodeKey(String? base64Key) => (super.noSuchMethod(
        Invocation.method(
          #decodeKey,
          [base64Key],
        ),
        returnValue: _i16.Uint8List(0),
      ) as _i16.Uint8List);

  @override
  String encodeBytes(_i16.Uint8List? bytes) => (super.noSuchMethod(
        Invocation.method(
          #encodeBytes,
          [bytes],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #encodeBytes,
            [bytes],
          ),
        ),
      ) as String);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i17.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i16.Uint8List> encrypt(_i16.Uint8List? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [data],
        ),
        returnValue: _i3.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
      ) as _i3.Future<_i16.Uint8List>);

  @override
  _i3.Future<_i16.Uint8List> decrypt(_i16.Uint8List? encryptedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [encryptedData],
        ),
        returnValue: _i3.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
      ) as _i3.Future<_i16.Uint8List>);

  @override
  _i3.Future<void> encryptFile(
    String? inputPath,
    String? outputPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptFile,
          [
            inputPath,
            outputPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> decryptFile(
    String? inputPath,
    String? outputPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFile,
          [
            inputPath,
            outputPath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> encryptString(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptString,
          [plaintext],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #encryptString,
            [plaintext],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> decryptString(String? encryptedBase64) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptString,
          [encryptedBase64],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #decryptString,
            [encryptedBase64],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  bool isLikelyEncrypted(_i16.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #isLikelyEncrypted,
          [data],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> ensureKeyInitialized() => (super.noSuchMethod(
        Invocation.method(
          #ensureKeyInitialized,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i18.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i3.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i3.Future<_i2.Database>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, dynamic>? values, {
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
          {#conflictAlgorithm: conflictAlgorithm},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> rawExecute(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawExecute,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<T> transaction<T>(
          _i3.Future<T> Function(_i2.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i15.ifNotNull(
              _i15.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<List<Object?>> batch(
    void Function(_i2.Batch)? operations, {
    bool? noResult,
    bool? continueOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [operations],
          {
            #noResult: noResult,
            #continueOnError: continueOnError,
          },
        ),
        returnValue: _i3.Future<List<Object?>>.value(<Object?>[]),
      ) as _i3.Future<List<Object?>>);

  @override
  _i3.Future<List<String>> searchDocuments(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, dynamic>?> getById(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> exists(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [
            table,
            id,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> count(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDatabase() => (super.noSuchMethod(
        Invocation.method(
          #deleteDatabase,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> vacuum() => (super.noSuchMethod(
        Invocation.method(
          #vacuum,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rebuildFtsIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildFtsIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getDatabasePath() => (super.noSuchMethod(
        Invocation.method(
          #getDatabasePath,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getDatabasePath,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<int> getDatabaseVersion() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseVersion,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllTags({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getTagByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagByName,
          [name],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<String>> getTagIdsForDocument(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagIdsForDocument,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTagsForDocument(
          String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagsForDocument,
          [documentId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getDocumentIdsForTag(String? tagId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentIdsForTag,
          [tagId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> addTagToDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTagFromDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setDocumentTags(
    String? documentId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDocumentTags,
          [
            documentId,
            tagIds,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, int>> getTagDocumentCounts() => (super.noSuchMethod(
        Invocation.method(
          #getTagDocumentCounts,
          [],
        ),
        returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDocumentsWithAnyTag(
          List<String>? tagIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsWithAnyTag,
          [tagIds],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDocumentsWithAllTags(
          List<String>? tagIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsWithAllTags,
          [tagIds],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<bool> documentHasTag(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #documentHasTag,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> tagNameExists(String? name) => (super.noSuchMethod(
        Invocation.method(
          #tagNameExists,
          [name],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i19.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Document> createDocument({
    required String? title,
    required String? sourceFilePath,
    String? description,
    String? thumbnailSourcePath,
    int? pageCount = 1,
    String? folderId,
    bool? isFavorite = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocument,
          [],
          {
            #title: title,
            #sourceFilePath: sourceFilePath,
            #description: description,
            #thumbnailSourcePath: thumbnailSourcePath,
            #pageCount: pageCount,
            #folderId: folderId,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #createDocument,
            [],
            {
              #title: title,
              #sourceFilePath: sourceFilePath,
              #description: description,
              #thumbnailSourcePath: thumbnailSourcePath,
              #pageCount: pageCount,
              #folderId: folderId,
              #isFavorite: isFavorite,
            },
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document?> getDocument(
    String? id, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<_i4.Document?>.value(),
      ) as _i3.Future<_i4.Document?>);

  @override
  _i3.Future<List<_i4.Document>> getAllDocuments({
    bool? includeTags = false,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> getDocumentsInFolder(
    String? folderId, {
    bool? includeTags = false,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsInFolder,
          [folderId],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> getFavoriteDocuments(
          {bool? includeTags = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDocuments,
          [],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<int> getDocumentCount() => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getDecryptedFilePath(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedFilePath,
          [document],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getDecryptedFilePath,
            [document],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String?> getDecryptedThumbnailPath(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailPath,
          [document],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i4.Document> updateDocument(_i4.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocument,
            [document],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentFile(
    _i4.Document? document,
    String? newSourceFilePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentFile,
          [
            document,
            newSourceFilePath,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentFile,
            [
              document,
              newSourceFilePath,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentThumbnail(
    _i4.Document? document,
    String? newThumbnailPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentThumbnail,
          [
            document,
            newThumbnailPath,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentThumbnail,
            [
              document,
              newThumbnailPath,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> updateDocumentOcr(
    String? documentId,
    String? ocrText, {
    _i4.OcrStatus? status = _i4.OcrStatus.completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentOcr,
          [
            documentId,
            ocrText,
          ],
          {#status: status},
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #updateDocumentOcr,
            [
              documentId,
              ocrText,
            ],
            {#status: status},
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> toggleFavorite(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [documentId],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #toggleFavorite,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<_i4.Document> moveToFolder(
    String? documentId,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToFolder,
          [
            documentId,
            folderId,
          ],
        ),
        returnValue: _i3.Future<_i4.Document>.value(_FakeDocument_2(
          this,
          Invocation.method(
            #moveToFolder,
            [
              documentId,
              folderId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Document>);

  @override
  _i3.Future<void> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocuments(List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocuments,
          [documentIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cleanupTempFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTempFiles,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getDocumentTags(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentTags,
          [documentId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> addTagToDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTagFromDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Document>> getDocumentsByTag(
    String? tagId, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByTag,
          [tagId],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<List<_i4.Document>> searchDocuments(
    String? query, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
          {#includeTags: includeTags},
        ),
        returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
      ) as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [OcrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOcrService extends _i1.Mock implements _i5.OcrService {
  MockOcrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.OcrLanguage> get availableLanguages => (super.noSuchMethod(
        Invocation.getter(#availableLanguages),
        returnValue: <_i5.OcrLanguage>[],
      ) as List<_i5.OcrLanguage>);

  @override
  _i3.Future<bool> initialize(
          {List<_i5.OcrLanguage>? languages = const [
            _i5.OcrLanguage.english
          ]}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#languages: languages},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  bool isLanguageAvailable(_i5.OcrLanguage? language) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageAvailable,
          [language],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i5.OcrResult> extractTextFromFile(
    String? imagePath, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromFile,
          [imagePath],
          {#options: options},
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextFromFile,
            [imagePath],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<_i5.OcrResult> extractTextFromBytes(
    _i16.Uint8List? bytes, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromBytes,
          [bytes],
          {#options: options},
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextFromBytes,
            [bytes],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<_i5.OcrResult> extractTextFromMultipleFiles(
    List<String>? imagePaths, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
    String? separator = '\n\n',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromMultipleFiles,
          [imagePaths],
          {
            #options: options,
            #separator: separator,
          },
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextFromMultipleFiles,
            [imagePaths],
            {
              #options: options,
              #separator: separator,
            },
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<_i5.OcrResult> extractTextWithProgress(
    List<String>? imagePaths, {
    _i5.OcrOptions? options = _i5.OcrOptions.defaultDocument,
    required void Function(
      int,
      int,
      _i5.OcrResult,
    )? onProgress,
    String? separator = '\n\n',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextWithProgress,
          [imagePaths],
          {
            #options: options,
            #onProgress: onProgress,
            #separator: separator,
          },
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_FakeOcrResult_3(
          this,
          Invocation.method(
            #extractTextWithProgress,
            [imagePaths],
            {
              #options: options,
              #onProgress: onProgress,
              #separator: separator,
            },
          ),
        )),
      ) as _i3.Future<_i5.OcrResult>);

  @override
  _i3.Future<bool> containsText(
    String? imagePath, {
    _i5.OcrLanguage? language = _i5.OcrLanguage.english,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsText,
          [imagePath],
          {#language: language},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getCacheSizeFormatted() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSizeFormatted,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getCacheSizeFormatted,
            [],
          ),
        )),
      ) as _i3.Future<String>);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i6.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.RecentSearch> get recentSearches => (super.noSuchMethod(
        Invocation.getter(#recentSearches),
        returnValue: <_i6.RecentSearch>[],
      ) as List<_i6.RecentSearch>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i6.SearchResults> search(
    String? query, {
    _i6.SearchOptions? options = const _i6.SearchOptions.defaults(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#options: options},
        ),
        returnValue: _i3.Future<_i6.SearchResults>.value(_FakeSearchResults_4(
          this,
          Invocation.method(
            #search,
            [query],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i6.SearchResults>);

  @override
  _i3.Future<List<String>> getSuggestions(
    String? partialQuery, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [partialQuery],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i6.RecentSearch>> getRecentSearches({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i3.Future<List<_i6.RecentSearch>>.value(<_i6.RecentSearch>[]),
      ) as _i3.Future<List<_i6.RecentSearch>>);

  @override
  _i3.Future<void> clearRecentSearches() => (super.noSuchMethod(
        Invocation.method(
          #clearRecentSearches,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeRecentSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #removeRecentSearch,
          [query],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rebuildIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildIndex,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getIndexSize() => (super.noSuchMethod(
        Invocation.method(
          #getIndexSize,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [FolderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderService extends _i1.Mock implements _i8.FolderService {
  MockFolderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.Folder> createFolder({
    required String? name,
    String? parentId,
    String? color,
    String? icon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [],
          {
            #name: name,
            #parentId: parentId,
            #color: color,
            #icon: icon,
          },
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #createFolder,
            [],
            {
              #name: name,
              #parentId: parentId,
              #color: color,
              #icon: icon,
            },
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder?> getFolder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFolder,
          [id],
        ),
        returnValue: _i3.Future<_i7.Folder?>.value(),
      ) as _i3.Future<_i7.Folder?>);

  @override
  _i3.Future<List<_i7.Folder>> getAllFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getRootFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRootFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getChildFolders(
    String? parentId, {
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildFolders,
          [parentId],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getDescendantFolders(String? parentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDescendantFolders,
          [parentId],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<List<_i7.Folder>> getFolderPath(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderPath,
          [folderId],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<int> getFolderDepth(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getFolderDepth,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getFolderCount() => (super.noSuchMethod(
        Invocation.method(
          #getFolderCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> folderExists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #folderExists,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getDocumentCount(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i8.FolderStats> getFolderStats(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderStats,
          [folderId],
        ),
        returnValue: _i3.Future<_i8.FolderStats>.value(_FakeFolderStats_6(
          this,
          Invocation.method(
            #getFolderStats,
            [folderId],
          ),
        )),
      ) as _i3.Future<_i8.FolderStats>);

  @override
  _i3.Future<bool> isFolderEmpty(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #isFolderEmpty,
          [folderId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i7.Folder> updateFolder(_i7.Folder? folder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolder,
          [folder],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #updateFolder,
            [folder],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> renameFolder(
    String? folderId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [
            folderId,
            newName,
          ],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #renameFolder,
            [
              folderId,
              newName,
            ],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> updateFolderColor(
    String? folderId,
    String? color,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolderColor,
          [
            folderId,
            color,
          ],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #updateFolderColor,
            [
              folderId,
              color,
            ],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> updateFolderIcon(
    String? folderId,
    String? icon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolderIcon,
          [
            folderId,
            icon,
          ],
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #updateFolderIcon,
            [
              folderId,
              icon,
            ],
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<_i7.Folder> moveFolder(
    String? folderId, {
    String? newParentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFolder,
          [folderId],
          {#newParentId: newParentId},
        ),
        returnValue: _i3.Future<_i7.Folder>.value(_FakeFolder_5(
          this,
          Invocation.method(
            #moveFolder,
            [folderId],
            {#newParentId: newParentId},
          ),
        )),
      ) as _i3.Future<_i7.Folder>);

  @override
  _i3.Future<void> deleteFolder(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [folderId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteFolderRecursive(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolderRecursive,
          [folderId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteFolders(List<String>? folderIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolders,
          [folderIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Folder>> searchFolders(
    String? query, {
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFolders,
          [query],
          {#orderBy: orderBy},
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);

  @override
  _i3.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<(_i7.Folder, int)>> getFolderHierarchy() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderHierarchy,
          [],
        ),
        returnValue:
            _i3.Future<List<(_i7.Folder, int)>>.value(<(_i7.Folder, int)>[]),
      ) as _i3.Future<List<(_i7.Folder, int)>>);

  @override
  _i3.Future<List<_i7.Folder>> getSelectableFolders(String? excludeFolderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectableFolders,
          [excludeFolderId],
        ),
        returnValue: _i3.Future<List<_i7.Folder>>.value(<_i7.Folder>[]),
      ) as _i3.Future<List<_i7.Folder>>);
}

/// A class which mocks [SignatureService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignatureService extends _i1.Mock implements _i10.SignatureService {
  MockSignatureService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i9.HandSignatureControl createControl(
          {_i10.SignatureOptions? options =
              const _i10.SignatureOptions.document()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createControl,
          [],
          {#options: options},
        ),
        returnValue: _FakeHandSignatureControl_7(
          this,
          Invocation.method(
            #createControl,
            [],
            {#options: options},
          ),
        ),
      ) as _i9.HandSignatureControl);

  @override
  _i3.Future<_i10.CapturedSignature> captureSignature(
    _i9.HandSignatureControl? control, {
    _i10.SignatureOptions? options = const _i10.SignatureOptions.document(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureSignature,
          [control],
          {#options: options},
        ),
        returnValue:
            _i3.Future<_i10.CapturedSignature>.value(_FakeCapturedSignature_8(
          this,
          Invocation.method(
            #captureSignature,
            [control],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i10.CapturedSignature>);

  @override
  _i3.Future<_i10.SavedSignature> saveSignature(
    _i10.CapturedSignature? signature, {
    required String? label,
    bool? setAsDefault = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSignature,
          [signature],
          {
            #label: label,
            #setAsDefault: setAsDefault,
          },
        ),
        returnValue:
            _i3.Future<_i10.SavedSignature>.value(_FakeSavedSignature_9(
          this,
          Invocation.method(
            #saveSignature,
            [signature],
            {
              #label: label,
              #setAsDefault: setAsDefault,
            },
          ),
        )),
      ) as _i3.Future<_i10.SavedSignature>);

  @override
  _i3.Future<List<_i10.SavedSignature>> getAllSignatures() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSignatures,
          [],
        ),
        returnValue: _i3.Future<List<_i10.SavedSignature>>.value(
            <_i10.SavedSignature>[]),
      ) as _i3.Future<List<_i10.SavedSignature>>);

  @override
  _i3.Future<_i10.SavedSignature?> getSignature(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSignature,
          [id],
        ),
        returnValue: _i3.Future<_i10.SavedSignature?>.value(),
      ) as _i3.Future<_i10.SavedSignature?>);

  @override
  _i3.Future<_i10.SavedSignature?> getDefaultSignature() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultSignature,
          [],
        ),
        returnValue: _i3.Future<_i10.SavedSignature?>.value(),
      ) as _i3.Future<_i10.SavedSignature?>);

  @override
  _i3.Future<int> getSignatureCount() => (super.noSuchMethod(
        Invocation.method(
          #getSignatureCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i10.SavedSignature> updateSignatureLabel(
    String? id,
    String? newLabel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSignatureLabel,
          [
            id,
            newLabel,
          ],
        ),
        returnValue:
            _i3.Future<_i10.SavedSignature>.value(_FakeSavedSignature_9(
          this,
          Invocation.method(
            #updateSignatureLabel,
            [
              id,
              newLabel,
            ],
          ),
        )),
      ) as _i3.Future<_i10.SavedSignature>);

  @override
  _i3.Future<_i10.SavedSignature> setDefaultSignature(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDefaultSignature,
          [id],
        ),
        returnValue:
            _i3.Future<_i10.SavedSignature>.value(_FakeSavedSignature_9(
          this,
          Invocation.method(
            #setDefaultSignature,
            [id],
          ),
        )),
      ) as _i3.Future<_i10.SavedSignature>);

  @override
  _i3.Future<void> clearDefaultSignature() => (super.noSuchMethod(
        Invocation.method(
          #clearDefaultSignature,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSignature(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSignature,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSignatures(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteSignatures,
          [ids],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i16.Uint8List> loadSignatureImage(
          _i10.SavedSignature? signature) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSignatureImage,
          [signature],
        ),
        returnValue: _i3.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
      ) as _i3.Future<_i16.Uint8List>);

  @override
  _i3.Future<_i10.SignedDocument> overlaySignatureOnDocument({
    required _i16.Uint8List? documentBytes,
    required _i16.Uint8List? signatureBytes,
    required _i20.Offset? position,
    required double? signatureWidth,
    double? opacity = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #overlaySignatureOnDocument,
          [],
          {
            #documentBytes: documentBytes,
            #signatureBytes: signatureBytes,
            #position: position,
            #signatureWidth: signatureWidth,
            #opacity: opacity,
          },
        ),
        returnValue:
            _i3.Future<_i10.SignedDocument>.value(_FakeSignedDocument_10(
          this,
          Invocation.method(
            #overlaySignatureOnDocument,
            [],
            {
              #documentBytes: documentBytes,
              #signatureBytes: signatureBytes,
              #position: position,
              #signatureWidth: signatureWidth,
              #opacity: opacity,
            },
          ),
        )),
      ) as _i3.Future<_i10.SignedDocument>);

  @override
  _i3.Future<_i10.SignedDocument> overlaySignatureOnDocumentById({
    required _i16.Uint8List? documentBytes,
    required String? signatureId,
    required _i20.Offset? position,
    required double? signatureWidth,
    double? opacity = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #overlaySignatureOnDocumentById,
          [],
          {
            #documentBytes: documentBytes,
            #signatureId: signatureId,
            #position: position,
            #signatureWidth: signatureWidth,
            #opacity: opacity,
          },
        ),
        returnValue:
            _i3.Future<_i10.SignedDocument>.value(_FakeSignedDocument_10(
          this,
          Invocation.method(
            #overlaySignatureOnDocumentById,
            [],
            {
              #documentBytes: documentBytes,
              #signatureId: signatureId,
              #position: position,
              #signatureWidth: signatureWidth,
              #opacity: opacity,
            },
          ),
        )),
      ) as _i3.Future<_i10.SignedDocument>);

  @override
  void clearControl(_i9.HandSignatureControl? control) => super.noSuchMethod(
        Invocation.method(
          #clearControl,
          [control],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasSignature(_i9.HandSignatureControl? control) => (super.noSuchMethod(
        Invocation.method(
          #hasSignature,
          [control],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<int> getStorageSize() => (super.noSuchMethod(
        Invocation.method(
          #getStorageSize,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getStorageSizeFormatted() => (super.noSuchMethod(
        Invocation.method(
          #getStorageSizeFormatted,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getStorageSizeFormatted,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> clearAllSignatures() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSignatures,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ImageProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProcessor extends _i1.Mock implements _i11.ImageProcessor {
  MockImageProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i11.ProcessedImage> enhanceFromFile(
    String? filePath, {
    _i11.EnhancementOptions? options = _i11.EnhancementOptions.none,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enhanceFromFile,
          [filePath],
          {
            #options: options,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #enhanceFromFile,
            [filePath],
            {
              #options: options,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> enhanceFromBytes(
    _i16.Uint8List? bytes, {
    _i11.EnhancementOptions? options = _i11.EnhancementOptions.none,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enhanceFromBytes,
          [bytes],
          {
            #options: options,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #enhanceFromBytes,
            [bytes],
            {
              #options: options,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> enhanceFromFileToFile(
    String? inputPath,
    String? outputPath, {
    _i11.EnhancementOptions? options = _i11.EnhancementOptions.none,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enhanceFromFileToFile,
          [
            inputPath,
            outputPath,
          ],
          {
            #options: options,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #enhanceFromFileToFile,
            [
              inputPath,
              outputPath,
            ],
            {
              #options: options,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> autoEnhance(
    _i16.Uint8List? bytes, {
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoEnhance,
          [bytes],
          {
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #autoEnhance,
            [bytes],
            {
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> convertToGrayscale(
    _i16.Uint8List? bytes, {
    bool? enhanceContrast = true,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertToGrayscale,
          [bytes],
          {
            #enhanceContrast: enhanceContrast,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #convertToGrayscale,
            [bytes],
            {
              #enhanceContrast: enhanceContrast,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> sharpen(
    _i16.Uint8List? bytes, {
    int? amount = 50,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sharpen,
          [bytes],
          {
            #amount: amount,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #sharpen,
            [bytes],
            {
              #amount: amount,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> adjustBrightness(
    _i16.Uint8List? bytes, {
    required int? amount,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustBrightness,
          [bytes],
          {
            #amount: amount,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #adjustBrightness,
            [bytes],
            {
              #amount: amount,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> adjustContrast(
    _i16.Uint8List? bytes, {
    required int? amount,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustContrast,
          [bytes],
          {
            #amount: amount,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #adjustContrast,
            [bytes],
            {
              #amount: amount,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> resize(
    _i16.Uint8List? bytes, {
    required int? maxWidth,
    required int? maxHeight,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resize,
          [bytes],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #resize,
            [bytes],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> crop(
    _i16.Uint8List? bytes, {
    required int? x,
    required int? y,
    required int? width,
    required int? height,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #crop,
          [bytes],
          {
            #x: x,
            #y: y,
            #width: width,
            #height: height,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #crop,
            [bytes],
            {
              #x: x,
              #y: y,
              #width: width,
              #height: height,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ProcessedImage> rotate(
    _i16.Uint8List? bytes, {
    required double? angle,
    _i11.ImageOutputFormat? outputFormat = _i11.ImageOutputFormat.jpeg,
    int? quality = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotate,
          [bytes],
          {
            #angle: angle,
            #outputFormat: outputFormat,
            #quality: quality,
          },
        ),
        returnValue:
            _i3.Future<_i11.ProcessedImage>.value(_FakeProcessedImage_11(
          this,
          Invocation.method(
            #rotate,
            [bytes],
            {
              #angle: angle,
              #outputFormat: outputFormat,
              #quality: quality,
            },
          ),
        )),
      ) as _i3.Future<_i11.ProcessedImage>);

  @override
  _i3.Future<_i11.ImageInfo> getImageInfo(_i16.Uint8List? bytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageInfo,
          [bytes],
        ),
        returnValue: _i3.Future<_i11.ImageInfo>.value(_FakeImageInfo_12(
          this,
          Invocation.method(
            #getImageInfo,
            [bytes],
          ),
        )),
      ) as _i3.Future<_i11.ImageInfo>);
}

/// A class which mocks [PDFGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPDFGenerator extends _i1.Mock implements _i12.PDFGenerator {
  MockPDFGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i12.GeneratedPDF> generateFromBytes({
    required List<_i16.Uint8List>? imageBytesList,
    _i12.PDFGeneratorOptions? options = const _i12.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromBytes,
          [],
          {
            #imageBytesList: imageBytesList,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i12.GeneratedPDF>.value(_FakeGeneratedPDF_13(
          this,
          Invocation.method(
            #generateFromBytes,
            [],
            {
              #imageBytesList: imageBytesList,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i12.GeneratedPDF>);

  @override
  _i3.Future<_i12.GeneratedPDF> generateFromFiles({
    required List<String>? imagePaths,
    _i12.PDFGeneratorOptions? options = const _i12.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromFiles,
          [],
          {
            #imagePaths: imagePaths,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i12.GeneratedPDF>.value(_FakeGeneratedPDF_13(
          this,
          Invocation.method(
            #generateFromFiles,
            [],
            {
              #imagePaths: imagePaths,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i12.GeneratedPDF>);

  @override
  _i3.Future<_i12.GeneratedPDF> generateFromPages({
    required List<_i12.PDFPage>? pages,
    _i12.PDFGeneratorOptions? options = const _i12.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromPages,
          [],
          {
            #pages: pages,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i12.GeneratedPDF>.value(_FakeGeneratedPDF_13(
          this,
          Invocation.method(
            #generateFromPages,
            [],
            {
              #pages: pages,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i12.GeneratedPDF>);

  @override
  _i3.Future<_i12.GeneratedPDF> generateToFile({
    required List<String>? imagePaths,
    required String? outputPath,
    _i12.PDFGeneratorOptions? options = const _i12.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateToFile,
          [],
          {
            #imagePaths: imagePaths,
            #outputPath: outputPath,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i12.GeneratedPDF>.value(_FakeGeneratedPDF_13(
          this,
          Invocation.method(
            #generateToFile,
            [],
            {
              #imagePaths: imagePaths,
              #outputPath: outputPath,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i12.GeneratedPDF>);

  @override
  _i3.Future<_i12.GeneratedPDF> generateSinglePage({
    required _i16.Uint8List? imageBytes,
    _i12.PDFGeneratorOptions? options = const _i12.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSinglePage,
          [],
          {
            #imageBytes: imageBytes,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i12.GeneratedPDF>.value(_FakeGeneratedPDF_13(
          this,
          Invocation.method(
            #generateSinglePage,
            [],
            {
              #imageBytes: imageBytes,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i12.GeneratedPDF>);

  @override
  _i3.Future<_i12.GeneratedPDF> generateSinglePageFromFile({
    required String? imagePath,
    _i12.PDFGeneratorOptions? options = const _i12.PDFGeneratorOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSinglePageFromFile,
          [],
          {
            #imagePath: imagePath,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i12.GeneratedPDF>.value(_FakeGeneratedPDF_13(
          this,
          Invocation.method(
            #generateSinglePageFromFile,
            [],
            {
              #imagePath: imagePath,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i12.GeneratedPDF>);
}

/// A class which mocks [ImageExporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageExporter extends _i1.Mock implements _i13.ImageExporter {
  MockImageExporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i13.ExportedImage> exportFromBytes(
    _i16.Uint8List? bytes, {
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
    String? originalFileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFromBytes,
          [bytes],
          {
            #options: options,
            #originalFileName: originalFileName,
          },
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #exportFromBytes,
            [bytes],
            {
              #options: options,
              #originalFileName: originalFileName,
            },
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.ExportedImage> exportFromFile(
    String? filePath, {
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFromFile,
          [filePath],
          {#options: options},
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #exportFromFile,
            [filePath],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.ExportedImage> exportToFile(
    _i16.Uint8List? bytes, {
    required String? outputPath,
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToFile,
          [bytes],
          {
            #outputPath: outputPath,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #exportToFile,
            [bytes],
            {
              #outputPath: outputPath,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.ExportedImage> exportFileToFile(
    String? inputPath,
    String? outputPath, {
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFileToFile,
          [
            inputPath,
            outputPath,
          ],
          {#options: options},
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #exportFileToFile,
            [
              inputPath,
              outputPath,
            ],
            {#options: options},
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.BatchExportResult> exportBatch({
    required List<_i16.Uint8List>? imageBytesList,
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBatch,
          [],
          {
            #imageBytesList: imageBytesList,
            #options: options,
          },
        ),
        returnValue:
            _i3.Future<_i13.BatchExportResult>.value(_FakeBatchExportResult_15(
          this,
          Invocation.method(
            #exportBatch,
            [],
            {
              #imageBytesList: imageBytesList,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i13.BatchExportResult>);

  @override
  _i3.Future<_i13.BatchExportResult> exportBatchFromFiles({
    required List<String>? imagePaths,
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBatchFromFiles,
          [],
          {
            #imagePaths: imagePaths,
            #options: options,
          },
        ),
        returnValue:
            _i3.Future<_i13.BatchExportResult>.value(_FakeBatchExportResult_15(
          this,
          Invocation.method(
            #exportBatchFromFiles,
            [],
            {
              #imagePaths: imagePaths,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i13.BatchExportResult>);

  @override
  _i3.Future<_i13.BatchExportResult> exportBatchToDirectory({
    required List<_i16.Uint8List>? imageBytesList,
    required String? outputDirectory,
    String? baseName = 'scan',
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportBatchToDirectory,
          [],
          {
            #imageBytesList: imageBytesList,
            #outputDirectory: outputDirectory,
            #baseName: baseName,
            #options: options,
          },
        ),
        returnValue:
            _i3.Future<_i13.BatchExportResult>.value(_FakeBatchExportResult_15(
          this,
          Invocation.method(
            #exportBatchToDirectory,
            [],
            {
              #imageBytesList: imageBytesList,
              #outputDirectory: outputDirectory,
              #baseName: baseName,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i13.BatchExportResult>);

  @override
  _i3.Future<_i13.ExportedImage> createThumbnail(
    _i16.Uint8List? bytes, {
    int? maxWidth = 300,
    int? maxHeight = 300,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThumbnail,
          [bytes],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #createThumbnail,
            [bytes],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
            },
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.ExportedImage> createPreview(
    _i16.Uint8List? bytes, {
    int? maxWidth = 800,
    int? maxHeight = 800,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPreview,
          [bytes],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #createPreview,
            [bytes],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
            },
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.ExportedImage> stitchVertical({
    required List<_i16.Uint8List>? imageBytesList,
    int? spacing = 0,
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stitchVertical,
          [],
          {
            #imageBytesList: imageBytesList,
            #spacing: spacing,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #stitchVertical,
            [],
            {
              #imageBytesList: imageBytesList,
              #spacing: spacing,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);

  @override
  _i3.Future<_i13.ExportedImage> stitchHorizontal({
    required List<_i16.Uint8List>? imageBytesList,
    int? spacing = 0,
    _i13.ImageExportOptions? options = const _i13.ImageExportOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stitchHorizontal,
          [],
          {
            #imageBytesList: imageBytesList,
            #spacing: spacing,
            #options: options,
          },
        ),
        returnValue: _i3.Future<_i13.ExportedImage>.value(_FakeExportedImage_14(
          this,
          Invocation.method(
            #stitchHorizontal,
            [],
            {
              #imageBytesList: imageBytesList,
              #spacing: spacing,
              #options: options,
            },
          ),
        )),
      ) as _i3.Future<_i13.ExportedImage>);
}
