// Mocks generated by Mockito 5.4.6 from annotations
// in aiscan/test/integration/ocr_pipeline_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:aiscan/core/storage/database_helper.dart' as _i10;
import 'package:aiscan/core/storage/document_repository.dart' as _i9;
import 'package:aiscan/features/documents/domain/document_model.dart' as _i3;
import 'package:aiscan/features/ocr/domain/ocr_service.dart' as _i2;
import 'package:aiscan/features/search/domain/search_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOcrResult_0 extends _i1.SmartFake implements _i2.OcrResult {
  _FakeOcrResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_1 extends _i1.SmartFake implements _i3.Document {
  _FakeDocument_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResults_4 extends _i1.SmartFake implements _i6.SearchResults {
  _FakeSearchResults_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OcrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOcrService extends _i1.Mock implements _i2.OcrService {
  MockOcrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.OcrLanguage> get availableLanguages => (super.noSuchMethod(
        Invocation.getter(#availableLanguages),
        returnValue: <_i2.OcrLanguage>[],
      ) as List<_i2.OcrLanguage>);

  @override
  _i5.Future<bool> initialize(
          {List<_i2.OcrLanguage>? languages = const [_i2.OcrLanguage.latin]}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#languages: languages},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  bool isLanguageAvailable(_i2.OcrLanguage? language) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageAvailable,
          [language],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i2.OcrResult> extractTextFromFile(
    String? imagePath, {
    _i2.OcrOptions? options = _i2.OcrOptions.defaultDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromFile,
          [imagePath],
          {#options: options},
        ),
        returnValue: _i5.Future<_i2.OcrResult>.value(_FakeOcrResult_0(
          this,
          Invocation.method(
            #extractTextFromFile,
            [imagePath],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.OcrResult>);

  @override
  _i5.Future<_i2.OcrResult> extractTextFromBytes(
    _i7.Uint8List? bytes, {
    _i2.OcrOptions? options = _i2.OcrOptions.defaultDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromBytes,
          [bytes],
          {#options: options},
        ),
        returnValue: _i5.Future<_i2.OcrResult>.value(_FakeOcrResult_0(
          this,
          Invocation.method(
            #extractTextFromBytes,
            [bytes],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.OcrResult>);

  @override
  _i5.Future<_i2.OcrResult> extractTextFromMultipleFiles(
    List<String>? imagePaths, {
    _i2.OcrOptions? options = _i2.OcrOptions.defaultDocument,
    String? separator = '\n\n',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromMultipleFiles,
          [imagePaths],
          {
            #options: options,
            #separator: separator,
          },
        ),
        returnValue: _i5.Future<_i2.OcrResult>.value(_FakeOcrResult_0(
          this,
          Invocation.method(
            #extractTextFromMultipleFiles,
            [imagePaths],
            {
              #options: options,
              #separator: separator,
            },
          ),
        )),
      ) as _i5.Future<_i2.OcrResult>);

  @override
  _i5.Future<_i2.OcrResult> extractTextWithProgress(
    List<String>? imagePaths, {
    _i2.OcrOptions? options = _i2.OcrOptions.defaultDocument,
    required void Function(
      int,
      int,
      _i2.OcrResult,
    )? onProgress,
    String? separator = '\n\n',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextWithProgress,
          [imagePaths],
          {
            #options: options,
            #onProgress: onProgress,
            #separator: separator,
          },
        ),
        returnValue: _i5.Future<_i2.OcrResult>.value(_FakeOcrResult_0(
          this,
          Invocation.method(
            #extractTextWithProgress,
            [imagePaths],
            {
              #options: options,
              #onProgress: onProgress,
              #separator: separator,
            },
          ),
        )),
      ) as _i5.Future<_i2.OcrResult>);

  @override
  _i5.Future<bool> containsText(
    String? imagePath, {
    _i2.OcrLanguage? language = _i2.OcrLanguage.latin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsText,
          [imagePath],
          {#language: language},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> getCacheSizeFormatted() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSizeFormatted,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getCacheSizeFormatted,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i9.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Document> createDocumentWithPages({
    required String? title,
    required List<String>? sourceImagePaths,
    String? description,
    String? thumbnailSourcePath,
    String? folderId,
    bool? isFavorite = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocumentWithPages,
          [],
          {
            #title: title,
            #sourceImagePaths: sourceImagePaths,
            #description: description,
            #thumbnailSourcePath: thumbnailSourcePath,
            #folderId: folderId,
            #isFavorite: isFavorite,
          },
        ),
        returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #createDocumentWithPages,
            [],
            {
              #title: title,
              #sourceImagePaths: sourceImagePaths,
              #description: description,
              #thumbnailSourcePath: thumbnailSourcePath,
              #folderId: folderId,
              #isFavorite: isFavorite,
            },
          ),
        )),
      ) as _i5.Future<_i3.Document>);

  @override
  _i5.Future<_i3.Document?> getDocument(
    String? id, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
          {#includeTags: includeTags},
        ),
        returnValue: _i5.Future<_i3.Document?>.value(),
      ) as _i5.Future<_i3.Document?>);

  @override
  _i5.Future<List<_i3.Document>> getAllDocuments({
    bool? includeTags = false,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i3.Document>>.value(<_i3.Document>[]),
      ) as _i5.Future<List<_i3.Document>>);

  @override
  _i5.Future<List<_i3.Document>> getDocumentsInFolder(
    String? folderId, {
    bool? includeTags = false,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsInFolder,
          [folderId],
          {
            #includeTags: includeTags,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i5.Future<List<_i3.Document>>.value(<_i3.Document>[]),
      ) as _i5.Future<List<_i3.Document>>);

  @override
  _i5.Future<List<_i3.Document>> getFavoriteDocuments(
          {bool? includeTags = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDocuments,
          [],
          {#includeTags: includeTags},
        ),
        returnValue: _i5.Future<List<_i3.Document>>.value(<_i3.Document>[]),
      ) as _i5.Future<List<_i3.Document>>);

  @override
  _i5.Future<int> getDocumentCount() => (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> getDecryptedPagePath(
    _i3.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPagePath,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDecryptedPagePath,
            [document],
            {#pageIndex: pageIndex},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> getDecryptedAllPages(_i3.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedAllPages,
          [document],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<int>> getDecryptedPageBytes(
    _i3.Document? document, {
    int? pageIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedPageBytes,
          [document],
          {#pageIndex: pageIndex},
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<_i7.Uint8List?> getDecryptedThumbnailBytes(
          _i3.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailBytes,
          [document],
        ),
        returnValue: _i5.Future<_i7.Uint8List?>.value(),
      ) as _i5.Future<_i7.Uint8List?>);

  @override
  _i5.Future<String?> getDecryptedThumbnailPath(_i3.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecryptedThumbnailPath,
          [document],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i3.Document> updateDocument(_i3.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #updateDocument,
            [document],
          ),
        )),
      ) as _i5.Future<_i3.Document>);

  @override
  _i5.Future<_i3.Document> updateDocumentThumbnail(
    _i3.Document? document,
    String? newThumbnailPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentThumbnail,
          [
            document,
            newThumbnailPath,
          ],
        ),
        returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #updateDocumentThumbnail,
            [
              document,
              newThumbnailPath,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Document>);

  @override
  _i5.Future<_i3.Document> updateDocumentOcr(
    String? documentId,
    String? ocrText, {
    _i3.OcrStatus? status = _i3.OcrStatus.completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentOcr,
          [
            documentId,
            ocrText,
          ],
          {#status: status},
        ),
        returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #updateDocumentOcr,
            [
              documentId,
              ocrText,
            ],
            {#status: status},
          ),
        )),
      ) as _i5.Future<_i3.Document>);

  @override
  _i5.Future<_i3.Document> toggleFavorite(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [documentId],
        ),
        returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #toggleFavorite,
            [documentId],
          ),
        )),
      ) as _i5.Future<_i3.Document>);

  @override
  _i5.Future<_i3.Document> moveToFolder(
    String? documentId,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToFolder,
          [
            documentId,
            folderId,
          ],
        ),
        returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #moveToFolder,
            [
              documentId,
              folderId,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Document>);

  @override
  _i5.Future<void> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDocuments(List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocuments,
          [documentIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getDocumentTags(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentTags,
          [documentId],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> addTagToDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeTagFromDocument(
    String? documentId,
    String? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDocument,
          [
            documentId,
            tagId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Document>> getDocumentsByTag(
    String? tagId, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByTag,
          [tagId],
          {#includeTags: includeTags},
        ),
        returnValue: _i5.Future<List<_i3.Document>>.value(<_i3.Document>[]),
      ) as _i5.Future<List<_i3.Document>>);

  @override
  _i5.Future<List<_i3.Document>> searchDocuments(
    String? query, {
    bool? includeTags = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
          {#includeTags: includeTags},
        ),
        returnValue: _i5.Future<List<_i3.Document>>.value(<_i3.Document>[]),
      ) as _i5.Future<List<_i3.Document>>);

  @override
  _i5.Future<void> cleanupTempFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTempFiles,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isReady() => (super.noSuchMethod(
        Invocation.method(
          #isReady,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i10.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i4.Database>.value(_FakeDatabase_2(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i4.Database>);

  @override
  bool get isFtsAvailable => (super.noSuchMethod(
        Invocation.getter(#isFtsAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> searchDocuments(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [query],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> rebuildFtsIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildFtsIndex,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> insert(
    String? table,
    Map<String, dynamic>? values,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<dynamic>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>?> getById(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [
            table,
            id,
          ],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<int> count(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<T> transaction<T>(
          _i5.Future<T> Function(_i4.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> exists(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [
            table,
            id,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllTags({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllFolders({String? orderBy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFolders,
          [],
          {#orderBy: orderBy},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPages,
          [documentId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<String>> getDocumentPagePaths(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPagePaths,
          [documentId],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, List<String>>> getBatchDocumentPagePaths(
          List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDocumentPagePaths,
          [documentIds],
        ),
        returnValue: _i5.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i5.Future<Map<String, List<String>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getDocumentPage(
    String? documentId,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPage,
          [
            documentId,
            pageNumber,
          ],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<int> insertDocumentPage({
    required String? documentId,
    required int? pageNumber,
    required String? filePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPage,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #filePath: filePath,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertDocumentPages(
    String? documentId,
    List<String>? filePaths,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocumentPages,
          [
            documentId,
            filePaths,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> deleteDocumentPages(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocumentPages,
          [documentId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateDocumentPagePath({
    required String? documentId,
    required int? pageNumber,
    required String? newFilePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentPagePath,
          [],
          {
            #documentId: documentId,
            #pageNumber: pageNumber,
            #newFilePath: newFilePath,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getDocumentPageCount(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentPageCount,
          [documentId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Map<String, List<String>>> getBatchDocumentTags(
          List<String>? documentIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchDocumentTags,
          [documentIds],
        ),
        returnValue: _i5.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i5.Future<Map<String, List<String>>>);

  @override
  _i5.Future<int> insertSearchHistory({
    required String? query,
    required String? timestamp,
    required int? resultCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSearchHistory,
          [],
          {
            #query: query,
            #timestamp: timestamp,
            #resultCount: resultCount,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getSearchHistory({
    int? limit,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {
            #limit: limit,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<int> deleteSearchHistory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSearchHistory,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i6.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.RecentSearch> get recentSearches => (super.noSuchMethod(
        Invocation.getter(#recentSearches),
        returnValue: <_i6.RecentSearch>[],
      ) as List<_i6.RecentSearch>);

  @override
  _i5.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i6.SearchResults> search(
    String? query, {
    _i6.SearchOptions? options = const _i6.SearchOptions.defaults(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#options: options},
        ),
        returnValue: _i5.Future<_i6.SearchResults>.value(_FakeSearchResults_4(
          this,
          Invocation.method(
            #search,
            [query],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i6.SearchResults>);

  @override
  _i5.Future<List<String>> getSuggestions(
    String? partialQuery, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [partialQuery],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i6.RecentSearch>> getRecentSearches({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i6.RecentSearch>>.value(<_i6.RecentSearch>[]),
      ) as _i5.Future<List<_i6.RecentSearch>>);

  @override
  _i5.Future<void> clearRecentSearches() => (super.noSuchMethod(
        Invocation.method(
          #clearRecentSearches,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRecentSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #removeRecentSearch,
          [query],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> rebuildIndex() => (super.noSuchMethod(
        Invocation.method(
          #rebuildIndex,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getIndexSize() => (super.noSuchMethod(
        Invocation.method(
          #getIndexSize,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
